/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package DemoImport.core;

public class GlyphParser {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GlyphParser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GlyphParser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        glyphJNI.delete_GlyphParser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static boolean loadFile(int cmdview, String filename) {
    return glyphJNI.GlyphParser_loadFile(cmdview, filename);
  }

}
