/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package DemoImport.core;

public class glyphJNI {
  public final static native boolean GlyphParser_loadFile(int jarg1, String jarg2);
  public final static native void delete_GlyphParser(long jarg1);
}
